name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      name:
        description: 'Release name'
        required: true
        default: 'v0.0.0'
      is-prerelease:
        description: 'Is this a pre-release?'
        required: true
        default: 'true'

jobs:
  release:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          echo "Installing build dependencies"
          dnf install -y \
            bash coreutils crun genisoimage \
            libselinux-devel libvirt-client \
            libvirt-daemon-driver-qemu \
            libvirt-daemon-log qemu-img \
            qemu-system-x86-core \
            shadow-utils util-linux \
            virtiofsd
          echo "Installing Rust toolchain"
          dnf install -y cargo

      - name: Build
        run: cargo build --release

      - name: Upload to Workflow
        uses: actions/upload-artifact@v3
        with:
          name: crun-qemu
          path: target/release/

      - name: Release
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.inputs.name }}-${{ github.sha }}
          prerelease: ${{ github.event.inputs.is-prerelease }}
          files: |
            target/release/crun-qemu
          token: ${{ secrets.GITHUB_TOKEN }}
